[workspace]
members = [
    "sysforward",
    "filters",
    "ptracer",
    "executor",
]
exclude = [
    "cb",
    "snapshotter",
]

[workspace.package]
version = "0.0.1"

[profile.dev]
debug = true
