[workspace]
members = [
    "sysfwd",
    "sysfwd_filter",
    "dbg/ptracer",
    "dbg/pexecutor",
]
exclude = [
    "cb",
    "snapshotter",
]

[workspace.package]
version = "0.0.1"

[profile.dev]
debug = true
